[package]
name = "fsm"                  # The package name used in wally
version = "1.0.0"             # Version number
author = "toxixsuff"
description = "A lightweight and extensible finite state machine for Roblox"
repository = "https://github.com/TheDynamicGit/Finite-State-Machine"  # GitHub URL
license = "MIT"
